name: Terraform Apply

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    # environment: ${{ env.ENVIRONMENT }}
    env:
      CONFIG_DIRECTORY: ./terraform
      STATE_BUCKET: tf-state-8864
      AWS_REGION: us-east-1
      ENVIRONMENT: development
      PROJECT_NAME: ${{ github.event.repository.name }}
    permissions:
      contents: write
      id-token: write
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    steps:
    - name: Terraform Apply
      id: terraform-apply
      uses: mleager/tf-shared-actions/.github/actions/terraform-apply@main
      with:
        oidc_role: ${{ secrets.OIDC_ROLE }}
        aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        project_name: ${{ env.PROJECT_NAME }}
        environment: ${{ env.ENVIRONMENT }}
        bucket: ${{ env.STATE_BUCKET }}
        key: ${{ env.PROJECT_NAME }}/terraform.tfstate
        region: ${{ env.AWS_REGION }}
        var_file: terraform.tfvars.${{ env.ENVIRONMENT }}
        make_commit_comment: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

