name: Terraform Plan

on:
  pull_request:

  # testing
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      CONFIG_DIRECTORY: ./terraform
      STATE_BUCKET: tf-state-8864
      AWS_REGION: us-east-1
      PROJECT_NAME: ${{ github.event.repository.name }}
      ENVIRONMENT: development
    # environment: ${{ env.ENVIRONMENT }}
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    steps:
    - name: Terraform Plan
      id: terraform-plan
      uses: mleager/tf-shared-actions/.github/actions/terraform-plan@main
      with:
        oidc_role: ${{ secrets.OIDC_ROLE }}
        aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        project_name: ${{ env.PROJECT_NAME }}
        environment: ${{ env.ENVIRONMENT }}
        bucket: ${{ env.STATE_BUCKET }}
        key: ${{ env.PROJECT_NAME }}/terraform.tfstate
        region: ${{ env.AWS_REGION }}
        var_file: terraform.tfvars.${{ env.ENVIRONMENT }}
        make_pr_comment: false
        github_token: ${{ secrets.GITHUB_TOKEN }}

