name: Terraform Destroy Bastion

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm resource destruction'
        required: true

env:
  CONFIG_DIRECTORY: ./terraform
  STATE_BUCKET: tf-state-bucket
  AWS_REGION: us-east-1
  ENVIRONMENT: development

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ env.ENVIRONMENT }}
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      VAR_FILE: terraform.tfvars.${{ env.ENVIRONMENT }}
    permissions:
      contents: write
      id-token: write
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.OIDC_ROLE }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      uses: mleager/tf-shared-actions/.github/actions/terraform-init@main
      with:
        bucket: ${{ env.STATE_BUCKET }}
        key: ${{ env.PROJECT_NAME }}/terraform.tfstate
        region: ${{ env.AWS_REGION }}

    - name: Confirm Destroy
      if: ${{ inputs.confirm_destroy != 'DESTROY' }}
      run: |
        echo "Destroy action was not confirmed. To destroy resources, you must type DESTROY in the confirmation input."
        exit 1

    - name: Terraform Destroy
      id: destroy
      run: |
        terraform destroy -target=aws_instance.bastion \
          -auto-approve -var-file=${{ env.VAR_FILE }} \
          2>&1 | tee destroy_output.txt
        echo "exit_code=$?" >> $GITHUB_OUTPUT

    - name: Capture Destroy Summary
      run: |
        SUMMARY=$(grep -A5 "Destroy complete!" destroy_output.txt | tail -n +2 || echo "No matching summary found.")
        echo "$SUMMARY" > destroy_summary.txt

    - name: Commit Comment (Destroy)
      uses: actions/github-script@v6
      env:
        EXIT_CODE: ${{ steps.destroy.outputs.exit_code }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const summary = fs.readFileSync('./terraform/destroy_summary.txt', 'utf8');
          const exitCode = parseInt(process.env.EXIT_CODE);
          const status = exitCode === 0 ? "✅ Success" : "❌ Failure";

          await github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: `### Terraform Destroy: ${status}

            <details><summary>Show Summary</summary>

            \`\`\`
            ${summary}
            \`\`\`
            </details>`
          });

          if (exitCode !== 0) {
            core.setFailed("Terraform destroy failed");
          }

